// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Argu")>]
[<assembly: AssemblyProductAttribute("Argu")>]
[<assembly: AssemblyDescriptionAttribute("A declarative command line and XML configuration parser for F# applications.")>]
[<assembly: AssemblyVersionAttribute("5.2.0")>]
[<assembly: AssemblyFileVersionAttribute("5.2.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Argu"
    let [<Literal>] AssemblyProduct = "Argu"
    let [<Literal>] AssemblyDescription = "A declarative command line and XML configuration parser for F# applications."
    let [<Literal>] AssemblyVersion = "5.2.0"
    let [<Literal>] AssemblyFileVersion = "5.2.0"
