// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Argu")>]
[<assembly: AssemblyProductAttribute("Argu")>]
[<assembly: AssemblyDescriptionAttribute("A declarative command line and XML configuration parser for F# applications.")>]
[<assembly: AssemblyVersionAttribute("4.2.1")>]
[<assembly: AssemblyFileVersionAttribute("4.2.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Argu"
    let [<Literal>] AssemblyProduct = "Argu"
    let [<Literal>] AssemblyDescription = "A declarative command line and XML configuration parser for F# applications."
    let [<Literal>] AssemblyVersion = "4.2.1"
    let [<Literal>] AssemblyFileVersion = "4.2.1"
