// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("3.5.0")>]
[<assembly: AssemblyFileVersionAttribute("3.5.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "3.5.0"
    let [<Literal>] AssemblyFileVersion = "3.5.0"
