name: Release

env:
  DOTNET_NOLOGO: true

on:
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      - name: Build
        run: ./build.sh -t Release
        shell: bash
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
